"""Keterangan tipe untuk `libsql`.

Paketnya berupa program terkompilasi (`libsql.cp310-win_amd64.pyd`) tanpa
keterangan tipe bawaan, jadi pemeriksa kode tidak bisa mengintip isinya dan
menandai tiap `libsql.connect(...)` sebagai salah.

Berkas ini TIDAK pernah dijalankan Python — hanya dibaca pemeriksa tipe.
Isinya sebatas yang dipakai `app/data/db.py` dan `app/data/unggah_turso.py`,
bukan seluruh API libsql.
"""

from collections.abc import Callable, Iterable, Sequence
from typing import Any

class Cursor:
    rowcount: int
    description: Any
    def fetchone(self) -> Any: ...
    def fetchall(self) -> list[Any]: ...
    def __iter__(self) -> Any: ...

class Connection:
    def execute(self, sql: str, parameters: Sequence[Any] = ...) -> Cursor: ...
    def executemany(self, sql: str, parameters: Iterable[Sequence[Any]]) -> Cursor: ...
    def executescript(self, sql: str) -> Cursor: ...
    def cursor(self) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def sync(self) -> None: ...

# Variabel, bukan `def`: cek mandiri `_check_jembatan_turso()` di `db.py`
# menggantinya sementara dengan pengganti yang tidak menyentuh jaringan.
connect: Callable[..., Connection]
